### ISSUE TITLE
add link based on tags to the graph

### ISSUE THREAD

**Issue by JeffeyChou** [airbytehq/glossary#8]
**Is your feature request related to a problem? Please describe.**
As seen in the Obsidian graph view, there are nodes and links between tags and md files. And mostly I write my md files in Obsidian, which influences the way I arrange my tags and aliases in the YAML frontmatter. However, I didn't see such links in QuartZ, so does the glossary. So I wonder if you can add this feature?

**Describe the solution you'd like**
Add a switch option to decide whether or not to enable the tags links.

Or add an attribute in the YAML frontmatter such as "categories" or "link", so that the md file with the same "categories" attribute will have visual links in the graph.

**Describe alternatives you've considered**
I have try to add a md link to my md files to act like a "tag" function so that to see these md files linked by another md file together. But its time-wasting and will contaminate my md files. 

**Additional context**
![image](https://user-images.githubusercontent.com/90391082/224485984-ce822b81-5fbc-4a40-adff-0526aea858a9.png)

**Comment by sspaeti** [comment]
Hi @JeffeyChou, thanks so much for reaching out. I'm not fully following your questions, but as it seems you are building your own Second Brain with Quartz, I recommend asking this question here: https://github.com/jackyzha0/quartz.

Quartz is the underlying framework we use for the Glossary. There is also a [Discord Forum](https://discord.gg/cRFFHYye7t) that is very helpful with questions. I hope that helps. I will close this issue is not related to the Glossary. If you have more questions about the Glossary, feel free to ask.
